### ISSUE TITLE
Add support for events

### ISSUE THREAD

**Issue by juanpablob** [drien/jquery-flipster#100]
Hello there! First of all, thank you for having this great plugin. It would be great have some events, specially when the item changes, either by clicking the item or using the arrows of the keyboard. For example, I'm using your plugin to display music album covers and I wanted to display the information of the selected item using `data-album-id`attribute but the plugin doesn't telling me which item was selected.

Hope this help you! Best,

Juan Pablo

**Comment by juanpablob** [comment]
I just noticed that exists an option called `onItemSwitch`, thats great, but this "event" doesn't fire up when the plugin starts, so I don't know the `currentItem` ;)

**Comment by shshaw** [comment]
It looks like the callback isn't called because [the index doesn't change](https://github.com/drien/jquery-flipster/blob/master/src/jquery.flipster.js#L428) when Flipster is initialized.

**Comment by juanpablob** [comment]
@shshaw that's right, but anyway, there was no update at all :(

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
