### ISSUE TITLE
Need a method "destroy"

### ISSUE THREAD

**Issue by idmedia-kannengiesser** [drien/jquery-flipster#101]
Hi,

first of all, thanks for this really great plugin! 
It works very well and got all I need...
Maybe not all I need. Is there any chance to get a destroy-method within the script?
For a project I need to switch the layout in mobile view, so I would like to destroy the binding for smartphone-views.

I saw that there has been a deestroy method before, why isn't it still in the script?

Thanks,
Inga

**Comment by mariavilaro** [comment]
This is still needed.

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
