### ISSUE TITLE
flipster('index');

### ISSUE THREAD

**Issue by arifulalam** [drien/jquery-flipster#102]
Hello,
I set following

``` javascript
$(function() {
    $_flipster = $(".coverflow").flipster({
        itemSelector: 'li:not(.hidden)',
        style: 'carousel',
    });
});
```

I used `li:not(.hidden)` so that I can apply css class `hidden` in runtime to hide any li (if required). Then I used following to hide all but required li and called `flipster('index');` which change the position of carousel from center to full right.

``` javascript
$(function(){
    $('a[data-category]').on('click', function(){
        $('.coverflow').children('ul').children('li:not(.'+$(this).attr('data-category')+')').addClass('hidden');
        $('.coverflow').children('ul').children('li.'+$(this).attr('data-category')+'').removeClass('hidden');
        $_flipster.flipster('index');
    })
});
```

![carousel](https://cloud.githubusercontent.com/assets/4211933/19273060/e9271886-8fec-11e6-9008-50b3ab92e116.png)

**Comment by LoganLehman** [comment]
Same here. @arifulalam - Have you figured out a way without the flipster team changing the codebase?

**Comment by arifulalam** [comment]
@LoganLehman 
I think, I used a div, like 
`<div class="load-flip"></div>`
for each category button I used
`<div class="dtw-category" data-category="abs">inside Image/text whatever required</div>`
then in script
`
jQuery(function(){
  jQuery('.dtw-category[data-category]').on('click', function(event){
      event.preventDefault();
       jQuery('.load-flip').children().remove();
      jQuery('.category-workouts').append('<div class="coverflow"><ul class="flip-items"></ul></div>');
      //Then appended <li>'s in between <ul> loading from json/ajax call/ preloaded hidden <li>

      var flipContainer = jQuery('.coverflow');
      var flipItemContainer = flipContainer.find('.flip-items');
      flipContainer.flipster({
         itemContainer: flipItemContainer,
         itemSelector: 'li',
         loop: true,
         style: 'coverflow',
         spacing: -0.5,
         scrollwheel: false,
         buttons: true,
         touch: false,
      });
   });
});
`

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
