### ISSUE TITLE
Add a successively narrow flat style

### ISSUE THREAD

**Issue by iVanilla** [drien/jquery-flipster#103]
I'm going to make a page similar to LoveLive! SIF for selecting the songs interface.
![LL SIF select songs](http://imgur.com/QT0GTyr.png)
I found that the flat style was Approaching  to what I wanted, but the other squares were not successively narrow. Could you add this style?

**Comment by shshaw** [comment]
Are you referring to the scaling or the distance? A custom style like that wouldn't be difficult.

**Comment by iVanilla** [comment]
@shshaw Both.
