### ISSUE TITLE
Firefox box-reflect

### ISSUE THREAD

**Issue by sunacc** [drien/jquery-flipster#105]
In firefox, -box-reflect is not supported, so we can't see the reflect effect on firefox, which is perfect on chrome and safari, is there any way to fix this problem and make reflection universal?

Current code is:
.flipster__item__content {
        transform-origin: 50% 100%;
        box-reflect: below 0 -webkit-gradient(linear, left bottom, left top, color-stop(0.05, rgba(255, 255, 255, 0.12)), color-stop(0.2, transparent));
        -webkit-box-reflect: below 0 -webkit-gradient(linear, left bottom, left top, color-stop(0.05, rgba(255, 255, 255, 0.12)), color-stop(0.2, transparent));
}

**Comment by shshaw** [comment]
`box-reflect` isn't standard and there aren't any standard cross-browser ways to implement that effect. If you're only concerned about Firefox, here's the only way I've seen to implement a similar effect: https://css-tricks.com/state-css-reflections/
