### ISSUE TITLE
Mouse wheel is not working 

### ISSUE THREAD

**Issue by ankitmadhwani24** [drien/jquery-flipster#109]
Hi 
I am using flipster
 `$(".coverflow").flipster({
        style: 'flat',
        spacing: -0.25,
        enableMousewheel: true,
        scrollwheel: true,
        touch:true,
        click:false
    });`
using the scrollwheel true but in firefox the scroll is not working 

Any solution please ?
Thanks in advance

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
