### ISSUE TITLE
more than 5 images the slider will not display the rest of images

### ISSUE THREAD

**Issue by lamaSonmez** [drien/jquery-flipster#111]
When I place more than 5 images the slider will not display them , and I tried to add margin-right to the <ul> container equals to the value of its translateX() which made  the images visible.
How can i fix this issue inside the js file

**Comment by olivercastle** [comment]
Yes, i also have the same issue. Did you get any further on this? I can display more than 5 but as soon as the width of the outer container is filled no more display.

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
