### ISSUE TITLE
Mousewheel and touch swiping not working

### ISSUE THREAD

**Issue by amiut** [drien/jquery-flipster#113]
Mousewheel and Touch doesn't work : 
```
$("#main_slider").flipster({
	style: 'flat',
	spacing: -0.7,
	enableMousewheel: true,
	scrollwheel: true,
	touch: true,
});
```
Does this need any third-party plugins or something or am i doing it wrong?

**Comment by TechnoLuna** [comment]
I am having the same issue. Did you ever get this resolved?

**Comment by amiut** [comment]
@TechnoLuna sadly not, i moved to Swiper plugin, it has a Cover Flow effect that works better, tough it wasn't exactly what i wanted.

**Comment by drien** [comment]
What browser versions and devices are you having trouble with? I just tested the demo with latest Chrome on Mac and Android as well as Safari for iPhone and things seemed to be working alright.

**Comment by shnacita** [comment]
Hi drien,
The touch Ipad is delayed/slow and difficult to grab. I am not sure why it is that. Perhaps the img is influencing on it?
`It is in an ipad -> version 9.3.5 (13G36) --> Model MC769x/A --> browser --> Chrome version 60.0.3112.89`

**Comment by fjmusick** [comment]
touch swiping is not working for me either on my implementation or the demo.  I am currently using Android 8.0.0  I have also checked my implementation using iPhone.

**Comment by incraigulous** [comment]
Yeah, same issue for me too. Swipe isn't working on Chrome/Android.

**Comment by fjmusick** [comment]
I have modified the base JavaScript file to alleviate this.  I focused on carousel as that is what we are using.  I hope to test it further after our next site launch.  As I don't have push access:
[http://www.thepros.com/js/jquery.flipster.js](url)

**Comment by incraigulous** [comment]
Great work. Normally you would fork the repo, make your changes, commit to
the forked repo, and create a pull request. You shouldn't need to push.

**Comment by fjmusick** [comment]
Thank you very much.  This is actually my first upload to GitHub.  It was about time I jumped on.

**Comment by incraigulous** [comment]
Sure thing! Welcome aboard! GitHub will change your life.

**Comment by drien** [comment]
By my testing this has been fixed by @fjmusick's PR which I've just merged–big props for tackling this and congratulations on your first github contribution!

I'll tag a new release with this fix in it.
