### ISSUE TITLE
Responsive Image Sizes

### ISSUE THREAD

**Issue by Cozmoz** [drien/jquery-flipster#114]
Hi,

I have applied Flipster to a site I am building but the images do not seem to changing size when resizing the browser and seem off center on mobile devices.

I was wondering if there was a way to resolve this? I would like the central image to take the width of the browser rather than overflow.

Please see below:

https://www.emergencytrade.com/demo/flipster.html

Kind Regards,

Costa

**Comment by assadnazar** [comment]
+1 to this!

Any update?

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
