### ISSUE TITLE
Expanded mode: Refresh/re-init slider 

### ISSUE THREAD

**Issue by eyeworkers-manuel** [drien/jquery-flipster#116]
Hi Flipster team,

I used your coverflow plugin for a web prorject and it is working great so far.
But now i want to implement an "expanded" view for this coverflow.

That means, when the user clicks on a button, the whole coverflow should be displayed bigger.
I thought, I could do this by simply increasing the size of the images via CSS, when the user clicked the expand button, but this results in a broken layout.

I think if I could refresh /re-init the slider with the new images sizes, this will fix my problem.
Any ideas how to get there?

PS: I read through some of the other issues posted here and found a mergerequest for a destroy method. I think this would bring me a hugh step closer to my goal. Any plans on when this will be merged into the master?

PPS: Sorry for my bad english! Hopefully I made myself clearly enough

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
