### ISSUE TITLE
html links in individual slide

### ISSUE THREAD

**Issue by joshmiller2010** [drien/jquery-flipster#117]
I'm building a flipster that has html elements in each slide. Some of those elements need to have html links to other pages, but it appears that the click state is being overwritten for the whole slide. The link url shows up in the status bar at the bottom of the browser, but the link is not registered. Any way to make this work? I thought maybe putting a high z-index on the link would work, but no change. Thanks

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
