### ISSUE TITLE
How do you find if it's already initialized without re-initializing?

### ISSUE THREAD

**Issue by ItsDanielHarris** [drien/jquery-flipster#122]
How would I find if it's already initialized without re-initializing it again? Here's what I tried, but it always initializes it in the `if` condition without the parameters.

>                 function init_flipster() {
>                         if ($(window).width() <= 614 && !($('.flipster').flipster())) {
>                                 $('.flipster').flipster({
>                                         style: 'carousel',
>                                         spacing: -0.5,
>                                         buttons: true,
>                                         loop: true,
>                                         touch: true
>                                 });                                       
>                         }
>                 }

**Comment by deimonhigh** [comment]
You could check if container has class `flipster--active`

````
 if ($(window).width() <= 614 && !($('.flipster').hasClass('flipster--active'))) {
                            $('.flipster').flipster({
                                    style: 'carousel',
                                    spacing: -0.5,
                                    buttons: true,
                                    loop: true,
                                    touch: true
                            });                                       
                    }
```

**Comment by rmilesson** [comment]
You could also just keep track of it yourself:

```
(function() {
    "use strict";

    is_flipster_initialized = false;

    function init_flipster() {
        if(is_flipster_initialized) {
            return;
        }

        // init flipster here
        
        is_flipster_initialized = true;
    }
}());
```

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
