### ISSUE TITLE
Slide content just disappears upon init (using default settings)

### ISSUE THREAD

**Issue by heronymo** [drien/jquery-flipster#124]
Hi.

I've been trying to figure out why this isn't working for a while and I can't figure it out. 

Tried with the latest version of jQuery, as well as the exact same version of jQuery that the demo runs on.

I've even tried loading it into a self-contained .html document (normally it's running within the WordPress front-page.php template), even previewed it locally. And still nothing.

The content that is to appear in the slides shows up for a second, but then disappears.

I've followed the setup instructions exactly. And I also used the same code as the default demo, only the element ID is different.

Any ideas? Please let me know of any additional info you need. Thanks!

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
