### ISSUE TITLE
Cyclic carousel?

### ISSUE THREAD

**Issue by msantelices** [drien/jquery-flipster#127]
Hi! In an [older demo](http://a.drien.com/jquery-flipster/) on the internet, the carousel is cyclic 
But in the current version when I use the carousel style like this:

`$( '.flipster' ).flipster({
	style: 'carousel',
	spacing: -0.25,
});`

When I reach to te last item, the carousel stop, like in the current demos.

There is any way to make the carousel act like in the first link I posted?

**Comment by Tebbott** [comment]
Does adding loop: true not make it cyclic?

**Comment by msantelices** [comment]
loop: true makes the carousel go all way back to the first item when it reach the last one in autoplay

**Comment by nickberens360** [comment]
I am interested in this as well. An "infinate" loop option would be great! Anyway to do this currently?

**Comment by channox32** [comment]
any updates on this ?

**Comment by anevaude** [comment]
I see what you mean, that effect was really cool. The current "loop" makes it go back to the first slide, but it's not a circle-like path.

**Comment by karmeljuk** [comment]
Same question. Any ideas how to make cyclic carousel?

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
