### ISSUE TITLE
Align Flipster to the right, rather than centering

### ISSUE THREAD

**Issue by Tebbott** [drien/jquery-flipster#128]
I know the conventional cover-flow style dictates that the current active item appears in the center of the list, however I'm looking to right align my coverflow, so you can only see the previous items, not the next.  Is this possible with Flipster?

**Comment by Tebbott** [comment]
OK, so you can use CSS to hide .flipster__item--future, which gives the appearance of flipster being right aligned.  Now to figure out how to initialise so that the last slide appears first.

**Comment by msantelices** [comment]
Hi!

Assuming your HTML looks like

```
<div class="flipster">
    <ul>
	<li>--Your content--</li>
	<li>--Your content--</li>
	<li>--Your content--</li>
    </ul>
</div>
```

You can hide the future items with css and use something like:

```
var last = $('.flipster ul li').length - 1;

$( '.flipster' ).flipster({
	spacing: -0.25,
	buttons: true,
	start: last
});
```

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
