### ISSUE TITLE
Add disabled class to next/prev buttons when no more slides to scroll

### ISSUE THREAD

**Issue by Tebbott** [drien/jquery-flipster#129]
As the title suggests, I'd like to be able to hide my next/prev buttons when there are no more slides to flip through.  Does anyone know if this is possible with the current plugin, or will the plugin code need tweaking?

**Comment by drien** [comment]
I think you're on the right track with the function you're describing, you get the current item as an arg to the onItemSwitch callback so you could do something like this (I haven't tested the code but in theory it should work):

```javascript
onItemSwitch: function(cur, prev) {
    $('.flipster__button--next, .flipster__button--prev').removeClass('disabled')

    if cur.siblings('.flipster__item--future').length == 0 {
        $('.flipster__button--next').addClass('disabled')
    }

    if cur.siblings('.flipster__item--past').length == 0 {
        $('.flipster__button--prev').addClass('disabled')
    }
}
```

Hope that's helpful.

It's a reasonable feature to consider adding in a future release so I'll leave this open.

**Comment by Tebbott** [comment]
Thanks for taking ythe time to help me with this.  Very much appreciated.

I've just implemented your code @amjadsheen however the disabled class is being added to both the previous and next buttons, every time, and the console logs are both being recorded.

**Comment by Tebbott** [comment]
I've used a mixture of the two responses thus far, and have the following:

`$('.flipster__button--next, .flipster__button--prev').removeClass('disabled');

		        if ($(currentItem).siblings('.flipster__item--future').length === 0 ) {
		            console.log('Hide Next');
		            $('.flipster__button--next').addClass('disabled');
		        }
		        if ($(currentItem).siblings('.flipster__item--past').length === 0 ) {
		            console.log('Hide Previous');
		            $('.flipster__button--prev').addClass('disabled');
		        }`

It's close, but it doesn't quite work still.  I'll have to create a codepen to try and illustrate what I'm getting, but unfortunately, don't have the time just now.

**Comment by amjadsheen** [comment]
Use css to hide disabled arrows
```javascript
.flipster__button--prev.disabled, .flipster__button--next.disabled {
	display: none;
}
```

**Comment by Tebbott** [comment]
Hi @amjadsheen - I have the CSS in place, the problem is as follows:

1. When you first arrive at the page, both arrows are displayed, even though there isnt a previous slide.

2. When you scroll to the second slide, the prev arrow disappears - even though there is now a previous slide.

3.  When you scroll to the third slide, both buttons are visible - this is correct.

4.  When you get to the final slide, the next button disappears - this is correct.

5.  When you then click the previous button, to go to the 2nd to last slide, the next button remains hidden.

You can see all this in action here - https://melodyvr.com/ - the section in question appears just below the hero area - the carousel that starts with KISS.

**Comment by Tebbott** [comment]
You sir, are an absolute legend.  There was one slight issue with the code, but it was simply an extra } at the end of the onItemSwitch function.  Apart from that, this code worked a dream.  Thank you so so much!

**Comment by amjadsheen** [comment]
Welcome.

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
