### ISSUE TITLE
Publish current version to npm

### ISSUE THREAD

**Issue by apertureless** [drien/jquery-flipster#130]
You forgot to publish the current version `1.1.3` to npm.

https://www.npmjs.com/package/jquery.flipster

**Comment by etalented** [comment]
yes please 2nd that!

**Comment by drien** [comment]
The npm package was initially published by @shshaw–could you add me as a collaborator on the npm project so I can make sure it's up to date? Thanks!

**Comment by shshaw** [comment]
@drien What is your NPM username so I can add you?

**Comment by drien** [comment]
Oops, my npm username is adelessert, @shshaw. Thanks!

**Comment by shshaw** [comment]
You should be on there now.

**Comment by drien** [comment]
Thanks! Just published the latest version.
