### ISSUE TITLE
Bottom shadow is not showing on latest firefox and Microsoft Edge

### ISSUE THREAD

**Issue by papazetis** [drien/jquery-flipster#132]
Hi.

Bottom shadow is not showing on latest Firefox(60.0.2) and Microsoft Edge(42.17134.1.0).

No issues on latest Chrome(67.0.3396.87)

**Comment by drien** [comment]
The reflection thing was a webkit-only feature when I first built this, and it looks like it never made it onto the standards track, so it'll probably need to be emulated with different CSS effects going forward, though it still has relatively decent coverage between Chrome and Safari: https://caniuse.com/#search=box-reflect

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
