### ISSUE TITLE
Iphones - Borders are Flickering while loading and scrolling

### ISSUE THREAD

**Issue by gobi004** [drien/jquery-flipster#135]
Hi,
After implemented in my design i could see the problem that borders are flickering while loading and scrolling in the below URLs  (specifically in iphone6 and above ).What could be the cause for this ?
URL: http://onextondtcdev.evoq-stg-i.com/all-about-acne 
http://onextondtcdev.evoq-stg-i.com/how-it-works

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
