### ISSUE TITLE
onItemSwitch seems to fire when I click on current item

### ISSUE THREAD

**Issue by tillinb** [drien/jquery-flipster#136]
I want to trigger a jQuery event (change classes of a text div) when the items change – and only when they change. The event handler onItemSwitch however seems to fire when I click on any of the items – even on the current item (which (of course) does not initiate a change). Is there a way really only focus on the actual "change" event?

ps: I am basically using the exact code as on this demo page:
http://a.drien.com/jquery-flipster/

Inside jQuery.flipster.js my settings currently look like this:

onItemSwitch: function(currentItem, previousItem){

		if( jQuery( "#content_stage" ).hasClass("expanded")) {
			jQuery( "#content_stage" ).removeClass( "expanded" );
			jQuery( "#content_stage" ).addClass( "hidden" );
			alert("alert");
		}
	},

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
