### ISSUE TITLE
Clicking on the third or later items from the current position with loop enabled moves to the last item

### ISSUE THREAD

**Issue by Spikatrix** [drien/jquery-flipster#139]
So, I have a flipster with some items in it.

Suppose that the current position (centered) is the first item (left most). When I click on the third or later items in the list, the flipster moves to the last item (right most) instead of moving to the item that I clicked on.

Similarly, when I'm on the last item (right most), and I click on the third-last or later items, the flipster moves to the first item (left most) instead of moving to the item that I clicked on.

This issue happens only when `loop: true` is set.

[Here is a jsfiddle](https://jsfiddle.net/fdLgrsm9/1/) showing the issue

**Comment by bdthemes** [comment]
same problem me too, can you fix this problem?

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
