### ISSUE TITLE
Coverflow speed scroll on iPad device

### ISSUE THREAD

**Issue by MrButterfly** [drien/jquery-flipster#14]
Hi,

I discovered Flipster with this demo example:
http://a.drien.com/jquery-flipster/

I prefer the utilisation of Touch Navigation on this old example, that is possible to have the same effect by changing the configuration of the current version of the plugin ?

Thanks.

**Comment by drien** [comment]
As part of drien/jquery-flipster/issues/38 I'll be revisiting some of the scrolling magic that doesn't seem to work so well right now.
