### ISSUE TITLE
How to trigger a function only on previous 

### ISSUE THREAD

**Issue by skt7** [drien/jquery-flipster#140]
I want to call a function only when the user goes back. I have seen that there is a functionality **onItemSwitch** where a function can be triggered but it does for both either going to previous item or next. I want to somehow call a function only when going to the previous item.

**Comment by Spikatrix** [comment]
`onItemSwitch` has two arguments `currentItem` and the `previousItem`. You can just use a condition to check what direction the flipster moved.

    if(currentItem < previousItem) {
        /* Moved backwards */
    }

(Assuming `loop: false`)

**Comment by drien** [comment]
Hi @skt7, your `onItemSwitch` callback function will receive the current and previous items as arguments, which should give you enough information to determine which direction things are moving in your handler.

**Comment by skt7** [comment]
I have clearly mentioned that I have an understanding of `onItemSwitch` callback function. I need a clearity of triggering a function while going back.
