### ISSUE TITLE
Animation bug in chrome and opera

### ISSUE THREAD

**Issue by Samiam519** [drien/jquery-flipster#143]
When switching between items in Chrome and Opera, you can see the item that was just moved jump as it's done moving. This issue does not exist in other browsers.

Chrome:
[https://vimeo.com/369621511](url)

Opera:
[https://vimeo.com/369623795](url)

Firefox:
[https://vimeo.com/369622980](url)

Edge:
[https://vimeo.com/369623386](url)

**Comment by lerouxm** [comment]
Hi, I'm having the exact same issues which make the usage of this plugin not a viable option for now.
That's a pity cause it has all I need and is very easy to implement. Let's hope somebody will find a solution :(

**Comment by drien** [comment]
Unfortunately this seems to be coming from a bug in the browser engine related to transitioning 3d elements that have a transform-origin set: https://bugs.chromium.org/p/chromium/issues/detail?id=986263&q=transform-origin&can=2

Removing the `transform-origin` and `-webkit-transform-origin` properties from `.flipster__item--future .flipster__item__content` and `.flipster__item--past .flipster__item__content` will fix the jumping issue, but it makes the coverflow look pretty bad.

I played around a bit with the demo trying to get back to the original appearance without setting the transform-origin, but couldn't get it quite right (I never really use CSS 3D transforms these days), though it seems like it's possible to get pretty close at least.

I'll subscribe to the Chromium issue and close this issue once they've pushed a fix.

**Comment by anevaude** [comment]
Just curious -- how come the demo works just fine in the same browsers? It looks flawless there.

http://brokensquare.com/Code/jquery-flipster/demo/

**Comment by drien** [comment]
I just got a notification that the chromium issue tracking this has been closed and I'm no longer seeing this behavior in Chrome, so I think we can consider this fixed.
