### ISSUE TITLE
Caption and Description to the right of flipster carousel

### ISSUE THREAD

**Issue by shivam-17** [drien/jquery-flipster#144]
How can I add content related to a particular slide on the right of the active slide . 
Description will be different for all other slides . 

![t](https://user-images.githubusercontent.com/17974579/72349496-a2434000-3702-11ea-9b38-940c99e8d324.png)

I have attached a sample for what I require ,

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
