### ISSUE TITLE
On Render Method

### ISSUE THREAD

**Issue by devilwacause** [drien/jquery-flipster#146]
I'd like an on render method to be available.  It'd help in that we can hide the container until the flipster is ready, then call a unhide so there isnt odd dom views.  For instance, if we are waiting for scripts to load, you can get "stacked" images until they load and flipster fires.  Or if you want to hide the parent container until it is rendered, you'll get a window between making the parent visible and the actual flipster rendering.

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
