### ISSUE TITLE
Highlighted image won't be in the center of the page.

### ISSUE THREAD

**Issue by olderhotter** [drien/jquery-flipster#147]
Hello, I tried to use Flipster on my page but the highlighted image seems to be off center. I have 4 images on the left, 1 in the middle, and 5 on the right. How can I resolve this?

Please kindly check this page :
https://syarifuddinnur.blogspot.com/p/models.html

Thank you so much in advance.

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
