### ISSUE TITLE
HTML links in slide not working

### ISSUE THREAD

**Issue by KirchnerKuM10** [drien/jquery-flipster#156]
Hi,

I have a similar problem like joshmiller2010 wrote on 10 Aug 2017: I've built a flipster that has html elements in each slide. Some of those elements need to have html links to other pages, but - in my case on a smartphone - it appears that the click state is being overwritten for the whole slide, so the link don't work properly. Any way to make this work? I thought maybe putting a high z-index on the link would work, but no change. 

Thank you in advance for any help!

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
