### ISSUE TITLE
carousel start:center not working after flipster('index')

### ISSUE THREAD

**Issue by ivzgrace** [drien/jquery-flipster#166]
Hi, I could have my carousel to start center after select change. I'm using jquery.ajax and reset the carousel by using the .flipster('index)

<pre>$("#product_reviews").on('change', function(event) {
event.preventDefault();
        var productslug = jQuery(this).val();
        var productopt = jQuery(this).find("option:selected").text();
    jQuery.ajax({
        url: '/wp-admin/admin-ajax.php',
        type: 'POST',
        data: {action:'data_fetch',optvalue: productslug, optname: productopt},
        dataType: 'html',
        success: function(data) {
            jQuery('#customer-reviews').html( data );
            $('#customer-reviews').flipster('index');
            $('#customer-reviews').addClass('flipster flipster--transform flipster--carousel flipster--click flipster--active');
            $('#customer-reviews').attr('tabindex',0);
            $('#customer-reviews').flipster({
                style: 'carousel',
                start: 'center',
                spacing: -0.5,
                loop: true,
                scrollwheel: false,
                autoplay: false,
                buttons:true,
            });    
        }
    });   
});</pre>
Before Select change:
![image](https://user-images.githubusercontent.com/2247363/192626112-48bfb35c-868a-43a2-8786-e03925b32912.png)

After Select change Ajax
![image](https://user-images.githubusercontent.com/2247363/192626260-39e777de-0e98-455e-83c7-84194c335083.png)

Does anyone experience this kind of issue? Any help is much appreciated.

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
