### ISSUE TITLE
Conflict with bootstrap carousel

### ISSUE THREAD

**Issue by torchdevelopment** [drien/jquery-flipster#19]
Firstly, what a great implementation of overflow and keep up the good work.  Secondly, I have come across a small issue concerning flipster and the bootstrap carousel, the problem is once the flipster js is loaded it stops the bootstrap carousel from working (scrolling stops working entirely).
Would you have any suggestions as to a possible fix?

Regards

**Comment by drien** [comment]
Closing as I haven't heard about this from other people, and it's a bit of an edge case of an old bootstrap and old browser versions.
