### ISSUE TITLE
Is it possible to Insert and Remove items from coverflow style?

### ISSUE THREAD

**Issue by JeganGitHub** [drien/jquery-flipster#24]
Is it possible to Insert and Remove items from coverflow style? I tried removing the li element removed through JQ and I still see an empty space there, Also I want dynamically add an item into the specified index position. Is it possible? Thanks and appreciate any help on this.

**Comment by drien** [comment]
I like this idea but as I'm cleaning up the issues to clarify milestones for a 0.4 release I'm going to shelve it for the future.
