### ISSUE TITLE
Vertical swipe on iOS

### ISSUE THREAD

**Issue by racinggrinner** [drien/jquery-flipster#31]
When testing flipster on iOS (iphone5/ipad), It is difficult to scroll vertically when the screen is filled with the flipster widget. 

You need to find an area not used by the flipster widget to scroll down. 

Is there any way to force flipster not to capture vertical swipes? 

Many Thanks

**Comment by drien** [comment]
Good catch @SamHoltby! I'll make sure your fix makes it into the default behavior.

**Comment by drien** [comment]
Thanks again, fixed in the v0.4 branch!

**Comment by SamHoltby** [comment]
No worries!
