### ISSUE TITLE
How to refresh Flipster ?

### ISSUE THREAD

**Issue by anonymous17** [drien/jquery-flipster#32]
How can we refresh flipster plugin ? Lets say we initialized plugin and it works fine, now if onchange event of some dropdown i have to re-initialize li items under ul container which is defined for the flipster. How should be refresh control so images are shown properly ?

**Comment by shshaw** [comment]
As of version 1.0, you can use the public method 'index', as you can see in this [simple demo](http://codepen.io/shshaw/pen/MKmajd?editors=001)

```js
flipContainer.flipster('index');
```

**Comment by NicolasVanhecke** [comment]
@anonymous17 I have tried this very similar to what you are saying.
I check which element of the list has the class `flipster__item--current` (meaning it is the active slide). That way I can create a infobar which says (photo 1 of 8). To update this I destroy and re-init the flipster. This works only once.. I get 'photo 1 of 8', then I click the next button and get 'photo 2 of 8', when I click the next button again I get this error in my console: `Uncaught TypeError: Cannot read property 'length' of undefined - jquery.flipster.js:412`

Any insights?
