### ISSUE TITLE
Vertical of Past & Future items not the same

### ISSUE THREAD

**Issue by jnschrag** [drien/jquery-flipster#34]
Hi there,

This might not be a bug, but I wanted to ask if anybody else had an issue with the past & future items not being vertically positioned the same? I haven't made any changes to the javascript or to the CSS file, but on my project, the "future" items are located about 50px closer to the top of the container than the "past" items are. I can sort of fix it by playing with the transformation and scale, but then they look uneven in a different way.

Was just wondering if anybody else was having this issue and had any suggestions for a solution? Thanks!

**Comment by drien** [comment]
I'm not able to replicate and nobody else has chimed in, so I'll close this for now.
