### ISSUE TITLE
Possible to scroll through images on swipe of track pad and/or on horizontal scroll bar in desktop?

### ISSUE THREAD

**Issue by okadots** [drien/jquery-flipster#38]
Me again :/

Looking to see if it's possible to scroll through the images using a swipe on the track pad and/or on scrolling horizontally in the browser.

**Comment by drien** [comment]
It is supposed to be possible, but it seems that that feature is pretty terrible right now and maybe shouldn't even exist if it can't be made better than it is right now.

**Comment by shshaw** [comment]
Horizontal scrolls now work in version 1.0. Give it a shot!
