### ISSUE TITLE
Carousel images not loading full size in Firefox

### ISSUE THREAD

**Issue by seanforyou23** [drien/jquery-flipster#39]
Hi, I have the following issue:

When loading the page for the first time, all images in the carousel display at a very small size. Subsequent loads display images at full size as intended. You can replicate by hard refreshing (holding shift and refreshing the page). Seems to only happen in Firefox. I'm using FF version 32.0.1 on a mac.

I really like this flipster library, and will be using it on the home page of a large site if I can get this resolved. Currently in development so time is of the essence. Thank you!

![hardrefreshinitialload](https://cloud.githubusercontent.com/assets/5942899/4321926/fa4e41a8-3f43-11e4-951e-ab15bc4d927d.png)

![subsequentrefresh](https://cloud.githubusercontent.com/assets/5942899/4321934/05ceada6-3f44-11e4-8136-41b5cf1e83f9.png)

**Comment by drien** [comment]
I noticed this in FF when the bug was first reported, but I'm not able to replicated it anymore with the latest version of Firefox. I'll take a closer as part of trying to fix the loading issues across the board.

**Comment by shshaw** [comment]
This is likely fixed in 1.0. Not having any issues in Firefox in the demos. Please test out the new version and let us know if this is still occuring!
