### ISSUE TITLE
Missing -webkit-box-reflect in Chrome

### ISSUE THREAD

**Issue by azzcatdesign** [drien/jquery-flipster#41]
Hi Adrien,

I'm using Flipster Coverflow. Looks/works great in Safari. But in Chrome, the reflection doesn't display–unless I toggle -webkit-box-reflect rule off and on in Inspector. OR, I can just turn off on of the transition rules and then the reflection magically displays. So add, b/c the Flipster demo displays fine in Chrome. 

I'm using it in a WordPress theme. I've also overridden some CSS. Can't figure if it's something not quite right in my code, or a weird Chrome bug.

Any Ideas?

Thanks,
Catherine
![initial_view](https://cloud.githubusercontent.com/assets/689117/4582421/366a1a86-4fe8-11e4-8185-71194140ed74.jpg)
![toggle_off_transition_rule](https://cloud.githubusercontent.com/assets/689117/4582429/49543366-4fe8-11e4-9486-4e1a356969c5.jpg)

**Comment by drien** [comment]
Thanks for reporting this, @azzcatdesign! I'm seeing the same thing, not sure of the cause but I'll try to diagnose it for the next release

**Comment by azzcatdesign** [comment]
Thanks @drien! Keep me posted. :)

**Comment by efbi** [comment]
Hi, i'm using this plugin too but the reflect doesn't work too.. i don't know if u found the problem ? 
Thanks :)

(Im using the theme mystile from woocommerce)

**Comment by shshaw** [comment]
Can you try the latest release, version 1.0? With those styles, I'm showing the reflections in the latest version of Chrome and Safari.
