### ISSUE TITLE
Current Image selected

### ISSUE THREAD

**Issue by fdoped** [drien/jquery-flipster#42]
Dear all,

It is possible to retrieve the index of the selected image on Flipster?

Best regards,

Flavio

**Comment by CharellKing** [comment]
why "-1"  is always returned by "$('.flip-current').index()"

**Comment by shshaw** [comment]
@CharellKing That depends on your exact setup and what you want to accomplish. You probably should be doing something like `$('.flipster__item').index('flipster__item--current');` to retrieve the index of the current item. See the [jQuery docs on `index`](http://api.jquery.com/index/) for more on how to get the result you're looking for.

**Comment by CharellKing** [comment]
thank you, i listen  the "onItemChange' event, it works for me

**Comment by edgarMejia** [comment]
I have the same problem.
