### ISSUE TITLE
Show images only when refresh

### ISSUE THREAD

**Issue by fdoped** [drien/jquery-flipster#45]
Hi,

I am using flipster in Carousel mode, but sometimes the images only appear refreshing the page.
It is not always, but sometimes it happens...

Anybody knows how to solve it?

Best regards,

Flavio

**Comment by nickfranklin** [comment]
I have the same issue - seems the <ul> element is being assigned width and height of 0px - no idea why

**Comment by nickfranklin** [comment]
I managed to resolve my problems with Carousel by commenting out this line:
if ( settings.style === 'carousel' ) { _flipItemsOuter.width(_flipItems.width()); }

**Comment by fdoped** [comment]
nickfranklin,

Wish you good luck to solve it. Once I could not solve this problem, I am using another plugin.

Regards!

**Comment by drien** [comment]
I think this is related to drien/jquery-flipster/issues/5
