### ISSUE TITLE
Autoplay

### ISSUE THREAD

**Issue by devensonas** [drien/jquery-flipster#46]
Hi, is it possible to make this plug in autorotate in caurusel stile? please post me where to put code and what i need to write to do this? thanks.

**Comment by GrandSam** [comment]
Hello, 
Late Answer, but today, your question is mine too ^_^

Here is a way to do it, with carousel style :
```
<script>
	$(function(){ 
		$(".flipster").flipster({
			style: 'carousel'
		});
	});
	// Go to "Right" picture after 3 seconds
	setInterval(function(){
		$(".flipster").flipster(
			'jump', 'right'
		);
	},3000);
</script>

**Comment by drien** [comment]
Thanks for answering this issue @GrandSam! I may try to work this into the next release.
