### ISSUE TITLE
Keyboard navigation on other component is updating flipster

### ISSUE THREAD

**Issue by warcops** [drien/jquery-flipster#50]
When we have multiple flipster on the page and use keyboard to navigate through the first flipster, the successive flipsters are getting updated as well.

On investigation, I noticed that you are registering the keyboard events on the body, without checking the target of the event.

My suggestion would be to check if ".flip-content" from the present flipster is present in the "parents" tree of the event's target and only then call the jump function.

**Comment by shshaw** [comment]
This is fixed in the version 1.0 branch. Please give that a shot and let me know if you encountered any other issues!
