### ISSUE TITLE
Android Swipe Bug

### ISSUE THREAD

**Issue by parakedista** [drien/jquery-flipster#56]
Device: Galaxy Note 3
Browser: Default

The first slider don't responds to the swipe gesture, but the sliders change automatically. In other android devices the swipe gesture works just fine.

Does anyone have the same issue, or some advice on how to solve this?

Thanks

**Comment by shshaw** [comment]
There's a significant re-write in the process of browser testing under the [v1 branch](https://github.com/drien/jquery-flipster/tree/v1). If you're able, would you mind trying the new version and let us know how it goes? Keep in mind the classes, CSS and options are quite different, so refer to the readme.md for more info.

**Comment by shshaw** [comment]
1.0 is now released. Please give it a shot and let us know if you still encounter this issue.
