### ISSUE TITLE
nav button position

### ISSUE THREAD

**Issue by DavidEmmel** [drien/jquery-flipster#57]
The nav buttons position on top of some items depending on screen width.

![button-overlap](https://cloud.githubusercontent.com/assets/11984709/8394698/38573960-1d14-11e5-8d60-7fe4cfc9841b.jpg)

**Comment by shshaw** [comment]
This isn't necessarily a bug, as there are many different combinations of options and styles that could produce this, and in fact may be desirable for some.

You could apply left & right padding on the main `.flipster` to give space for the absolutely positioned arrows to sit 'outside' of the main item flow.

Alternatively, if you're just wanting the user to be able to click those edge items, then disabling the arrows would be the best option.

**Comment by DavidEmmel** [comment]
I tried some padding and it didn't resolve it. I ended up creating the button code manually and using the callbacks to trigger the movement.

**Comment by shshaw** [comment]
Hm. I'll take another look at it. Thanks for following up.
