### ISSUE TITLE
IE nav button position

### ISSUE THREAD

**Issue by DavidEmmel** [drien/jquery-flipster#58]
I also noticed an issue with nav button position in IE 9/10/11. The button position is low compared to the "flat" setting and generates vertical scroll bars. I'm using the below CSS to tame it for now. I'll try and investigate to see if there is a better solution and get some screen shots as well.

```
@media all and (-ms-high-contrast:none)
 {
 .flipster__button { top: 15%; margin-top: -2em; } /* IE10 */
 *::-ms-backdrop, .flipster__button { top: 15% !important; margin-top: -2em; } /* IE11 */
 }
```

![ie-issue](https://cloud.githubusercontent.com/assets/11984709/8394688/252b33b4-1d14-11e5-938e-32c4bdbc342f.jpg)

**Comment by shshaw** [comment]
Thanks for the feedback!

Strange issue, not sure what's causing it. I haven't done a full browser test yet, but as I dig in there I'll take a closer look at this.

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
