### ISSUE TITLE
Won't initialize after AJAX call

### ISSUE THREAD

**Issue by RhanCandia** [drien/jquery-flipster#61]
I am loading the items via ajax and it returns HTML. I then insert that HTML into the container. Then initialize flipster. First call works just fine but the succeeding calls are breaking. It gives me stacked images after.

Anyone out there who can help?

**Comment by DaDanny** [comment]
If you are trying to add images after you have initialized flipster, you may experience issues.

I tried something similar, just pushing a new image to the image array, after flipster was already initialized, and the images were placed all weird.

My work around was waiting until all my images were loaded, then initializing flipster. If I ever had to add a new image after the fact, I removed flipster from the DOM and then reinitialized it.

**Comment by shshaw** [comment]
@DaDanny is correct. Currently everything is set up on initialization and won't compensate for added items. 

The 1.0 branch is almost ready for launch which includes an 'index' method that will allow items to be added/removed. So with 1.0, something like this should work:

```
$flipster = $("#myflip").flipster();

// items added...
$flipster.find('ul').append('<li>New Item</li>');

$flipster.flipster('index');
```
