### ISSUE TITLE
Update jQuery Plugin Entry

### ISSUE THREAD

**Issue by shshaw** [drien/jquery-flipster#62]
Stumbled across the entry for [jQuery Flipster on the jQuery plugin site](https://plugins.jquery.com/flipster/) and noticed it's still on 0.3.2.

Any idea how to update it?

I found this, but since I don't have the original `jquery.json` file, I'm not sure if it'll work: http://blog.npmjs.org/post/111475741445/publishing-your-jquery-plugin-to-npm-the-quick Doesn't look like jQuery Flipster is on NPM yet.

**Comment by haferje** [comment]
I'm kinda late, but this is on npm now: [jquery.flipster](https://www.npmjs.com/package/jquery.flipster)

**Comment by shshaw** [comment]
Yes, I pushed it to NPM a while back, but I don't know how to update the jQuery plugin directory's listing to use the NPM package.

**Comment by drien** [comment]
The jquery plugin repo is no longer, so I'm closing this.
