### ISSUE TITLE
Vertical jquery-flipster

### ISSUE THREAD

**Issue by polonanni** [drien/jquery-flipster#65]
Hello, is possible display in vertical?

we need display the carousel in vertical.

Thanks :)

**Comment by shshaw** [comment]
Currently Flipster is very much set up to be horizontal only (`translateX`, `margin-right`, left and right keyboard shortcuts, etc). 

Visually, you could fake it. My first inkling was to use just rotate everything, but that will interfere with the `center` method.
 ```
.flipster { transform: rotate(-90deg); }
.flipster__item__content > * { transform: rotate(90deg); }
```

But by using `.flipster__item { position: absolute; }`, the `center` method doesn't really do anything, so you can fake the movements. Here's a basic example: http://codepen.io/shshaw/pen/wKYwMj?editors=010

You'll need to add your own flavor to it, and of course none of the keyboard events or touch events will match, but that's the only option at the moment :-)

**Comment by polonanni** [comment]
ok, Good :)

but the button top don´t appear.

**Comment by shshaw** [comment]
Yeah, looks like you may need to play with the padding values to get it all lined up right. Since this isn't an officially supported featured, and so much will vary with your implementation I'll leave the exact values up to you.

If you need further help, just ask!
