### ISSUE TITLE
[CHROME] 3 Items on carousel mode still uses past and future

### ISSUE THREAD

**Issue by RhanCandia** [drien/jquery-flipster#66]
I am dynamically loading carousel items. Max is 6 and min is 1. Now, when I have 3 items, there are times when they pile up on a corner. current > prev > past.

I want it to stop using prev and next when I only have 3 items. How do I go about that? Thank you.

**Comment by RhanCandia** [comment]
My workaround was to loop through all children onSwitch and remove flip-past and flip-future classes.

**Comment by shshaw** [comment]
Hm. Could you provide a demo on [CodePen](http://codepen.io/pen) or screenshot of the pile up you're describing? Sounds like something odd is going on.
