### ISSUE TITLE
Links in next/previous slides

### ISSUE THREAD

**Issue by joe-smalley** [drien/jquery-flipster#67]
If I have a link in a next or previous slide and click on that slide to advance to the slide, and the cursor is over that link, the browser is taken to that link rather than advancing to that slide. Ideally the links should only function when clicked and the slide is the 'current' slide. Is that possible?

**Comment by joe-smalley** [comment]
I created a function to fix this (currently only works for one Flipster on the page though, 'myFlipster'):


	 	$('.flipster__item a').on('click', function ( e ) {

	 		if( $(this).parents('.flipster__item--past, .flipster__item--future').length ){
	 			e.stopPropagation();
	 			
	 			var slideIndex = $('.flipster__container .flipster__item').index( $(this).parents('.flipster__item') );

	 			if( slideIndex != -1){
	 				myFlipster.flipster('jump', slideIndex); // Jump to a specific index
	 			}
	 		}

	 	});

**Comment by shshaw** [comment]
That should be the default behavior: all slide clicks are captured to initiate the jump unless the slide is current. 

Try out this [demo](http://codepen.io/shshaw/pen/KVPyeg) and let me know if it works for you. 
If the links on non-current slides are not captured, provide your browser details. 

For reference, I tested the demo on Chrome 46.0.2490.86.
