### ISSUE TITLE
Destroy or 'push' function

### ISSUE THREAD

**Issue by stokesbga** [drien/jquery-flipster#68]
I am having the same issue here:
https://github.com/drien/jquery-flipster/issues/32

I want a dynamic flipster instance, and it would be nice to have 'add/remove' functions that allow me to populate flipster as needed. The 'destroy' function was never merged.

**Comment by shshaw** [comment]
In the public methods is an `index` function that will allow Flipster to update after you add or remove items like in this [simple `index` demo](http://codepen.io/shshaw/pen/MKmajd?editors=001)

```js
var flipContainer = $('.flipster'),
    flipItemContainer = flipContainer.find('.flip-items'),
    flipItem = flipContainer.find('li');

flipContainer.flipster({
  itemContainer: flipItemContainer,
  itemSelector: flipItem,
  loop: true,
  style: 'carousel',
  spacing: -0.5,
  scrollwheel: false,
  //nav: 'after',
  buttons: false
});
flipItem.eq(3).remove(); // Remove the 4th item (indexes are 0 based)
flipContainer.flipster('index'); // Reindex items
```

Are you expecting some other functionality with add/remove? Would you need the `destroy` function regardless?

**Comment by stokesbga** [comment]
i love you. no need for destroy. index was exactly what I was looking for. thanks.

**Comment by stokesbga** [comment]
SMALL thing - when I call index after adding an element and navigate to it for the FIRST time - whether it be clicking, arrows, or flipster('jump', n), there is no transition animation. Is there any workaround for this that you know of ?

**Comment by shshaw** [comment]
Hm... I suspect a class is missing for some reason on the new item when
index is run. How many items are you dealing with and where is the item
you're adding? (Beginning, end, etc)

**Comment by stokesbga** [comment]
The only thing I can see that looks different on a dynamically added element is that the z-index is 1, even when the selected element is immediately adjacent.

**Comment by stokesbga** [comment]
I want one function to create elements called addFlipsterItem, which will append a list item to the ul. Initially, addFlipsterItem will be called n times to load default elements. From then, the user has the option to call addFlipsterItem manually. I am having the issue if i initialize flipster with no list elements, or if i have 1 initial element or 10.

**Comment by stokesbga** [comment]
I fixed the animation jitter with:    

```
function noTransition() {
                self.css('transition', 'none');
                //_container.css('transition', 'none');   // --> I commented this out and the spacing/ animation were back to normal. weird. 
                _items.css('transition', 'none');
            }
```

**Comment by shshaw** [comment]
Odd... The `noTransition` function shouldn't be called when `index` is run, though it is called during a `resize` event. I'm not sure exactly why that would have any effect. Something to dig into further.

As for an `addFlipsterItem`, I don't know that it would be all that useful compared to fixing the `index` bugs so that users can add or remove items from wherever in the flow.

Could you create a demo of how exactly you're adding items dynamically so I can better understand the use case for all of this?

**Comment by stokesbga** [comment]
I will create a demo soon. So far, that fix to the noTransition function only applies to adding an element and calling index().

When I remove a list item and call index, flipster still recognizes that there is an element there, and focuses on empty space.

**Comment by shshaw** [comment]
Very strange. Updated my [Codepen demo](http://codepen.io/shshaw/pen/yePJXP?editors=001) to remove one item instead of adding, and it's working as expected. I'd love to see a demo of the behavior you're seeing.

**Comment by jagrutkosti** [comment]
I am facing the same problem as @stokesbga

**Comment by shshaw** [comment]
@jagrutkosti With the animation jitter or just adding items to a flipster instance?

**Comment by jagrutkosti** [comment]
With the animation jitter. Items are added successfully. I tried the solution mentioned by stokesbga but still it did not work for me.

**Comment by LoganLehman** [comment]
I am still running this, has this been addressed yet @stokesbga @shshaw ?

**Comment by shshaw** [comment]
This issue has varied quite a bit from the initial request. Please provide a demo (You can fork this [Codepen](https://codepen.io/shshaw/pen/qXVmRL)) of the behavior you're experiencing so it can be properly debugged and create a new issue.

I know there's probably quite a bit off in the library about the indexing when trying to add / remove items, but removing items should work correctly.
