### ISSUE TITLE
Error using Methods

### ISSUE THREAD

**Issue by macsupport** [drien/jquery-flipster#72]
Using this code:
````
var myFlipster = $('.my-flipster').flipster(); 
myFlipster.flipster('next'); // Next item
myFlipster.flipster('prev'); // Previous item 
````

I get this error in the console.
````
TypeError: H is undefined
v()
 jquery.flipster.min.js:2
a.fn.flipster/</E.next()
 jquery.flipster.min.js:2
a.fn.flipster/<()
 jquery.flipster.min.js:2
.each()
 jquery.min.js:2
n.prototype.each()
 jquery.min.js:2
a.fn.flipster()
 jquery.flipster.min.js:2
<anonymous>
 imageflow.js:379
n.event.dispatch()
 jquery.min.js:3
n.event.add/r.handle()
 jquery.min.js:3
 jquery.flipster.min.js:2:4432
````

**Comment by shshaw** [comment]
What browser? Testing the latest version of Flipster on Chrome, Firefox and Safari produced no errors.

http://codepen.io/shshaw/pen/RrxvPZ

**Comment by macsupport** [comment]
It seems the issue is using ````var myFlipster = $('.my-flipster').flipster();```` ,as shown in your example under methods. If I just  use ````var myFlipster = $('.my-flipster');````, no error. I wasn't sure why you had the variable include ````.flipster()```` as well.

**Comment by shshaw** [comment]
Hm, either way should work, since the `.flipster()` call on the jQuery collection should return that jQuery collection. I've updated the example like this and it still works:

```js
var button = document.createElement('button');
button.innerText = 'Next';
document.body.appendChild(button);
button.addEventListener('click',function(){
  flipper.flipster('next');
})

var flipContainer = $('.flipster'),
    flipItemContainer = flipContainer.find('.flip-items'),
    flipItem = flipContainer.find('li');

var flipper = flipContainer.flipster({
  itemContainer: flipItemContainer,
  itemSelector: flipItem,
  loop: true,
  style: 'carousel',
  spacing: -0.5,
  scrollwheel: false,
  //nav: 'after',
  buttons: false
});
```

**Comment by macsupport** [comment]
Thanks for your response. It may be an issue or conflict with other code in my project, then.
