### ISSUE TITLE
Issue with using "jump" in a select dropdown

### ISSUE THREAD

**Issue by macsupport** [drien/jquery-flipster#73]
I tried to use a simple dropdown to navigate items using 'jump' with the following code:
````
$("select").on("change", function() {
		var go = $(this).val();
                console.log(go);
		flipper.flipster('jump', go);	
		 }); 
````
I get very strange behavior with items disappearing, etc. 
Here is a fork of your codepen with the problem. 
[Example] (http://codepen.io/macsupport/pen/zrRWmp)
Any ideas?

**Comment by shshaw** [comment]
Found the issue. The `val` is coming through as a string. If you wrap that in `parseInt` so that a true number is passed to Flipster, then it works as expected.

[Updated example](http://codepen.io/shshaw/pen/Qymyyd?editors=0010)
