### ISSUE TITLE
 Pause  only pauses until the next or previous button is clicked

### ISSUE THREAD

**Issue by macsupport** [drien/jquery-flipster#75]
I have a function to set up a play and pause button like this:
````
var myFlipster = $('.container'); 
    var player = $("#player");
    if(player.hasClass('play'))
    {    
       player.toggleClass('play');  
  
		myFlipster.flipster('play', 3000); 
    }
    else 
    {
          player.toggleClass('pause');		 
		myFlipster.flipster('pause');
    }
````
It works except that after I pause the autoplay and click a next our previous button the autoplay starts again. Is there a way to set stop instead of pause so it does not do this? It seems pause is just a temporary function? Even when I use the console to set pause, it is only temporary.

**Comment by macsupport** [comment]
Still wondering if ```` myFlipster.flipster('pause');```` only sets pause on hover temporarily or does it actually pause the autoplay until ```` myFlipster.flipster('play', 3000);```` is called again? Trying to understand the function of pause since in my case, it is only temporary and unrelated to clicking ```` myFlipster.flipster('play', 3000);```` again. Thanks

**Comment by shshaw** [comment]
Hm. Looks like this is related to the `pauseOnHover` option. If you disable that, `flipster('pause')` should work as expected.

I think adding a `stop` method would help with this, as `pause` is more intended to temporarily halt the autoplay for the hover option.

**Comment by shshaw** [comment]
Give [1.1.0](https://github.com/drien/jquery-flipster/releases/tag/1.1.0) a try
