### ISSUE TITLE
Show flipster after resize bug

### ISSUE THREAD

**Issue by ryan-gavurin** [drien/jquery-flipster#8]
I have come across a rather interesting bug. I have a website that hides the flipster bit to show a form component, if the page is re-sized while flipster is hidden when you show the flipster bit it collopses. This is a pretty niche bug. Can javascript determine if the page size changes. Would this be worthy of a bug fix? I can have a go at building a fix.

Thanks

**Comment by shshaw** [comment]
This issue should be resolved in version 1.0. Please test it out and let us know if you encounter this again!
