### ISSUE TITLE
loop: true is not working.

### ISSUE THREAD

**Issue by saleemflashbox** [drien/jquery-flipster#80]
Hi I have downloaded the https://github.com/drien/jquery-flipster version , adding loop: true is not making looping in carousel, please help,
Following is my call to the carousel
 var coverflow = $("#sectionsSlider").flipster({
      itemContainer: 'ul',
      itemSelector: 'li',
      style: 'infinite-carousel',
      loop: true,
      touch: true,
      spacing: -0.43
    });

**Comment by shshaw** [comment]
Hi Saleem,

The 'infinite-carousel' style is not an official feature yet, but is under development. Download the version of flipster from https://github.com/drien/jquery-flipster/tree/infinite-loop and that should get it working, but keep in mind that it is not fully supported yet.

**Comment by shshaw** [comment]
Check out Issue #51 for more info and to join the discussion about how it should be implemented.

**Comment by priyamaran** [comment]
There is any option for auto slide?
