### ISSUE TITLE
Is it possible to set a max-width on each carousel item?

### ISSUE THREAD

**Issue by solarroger** [drien/jquery-flipster#81]
The items are fine when they're not that wide:
![image](https://cloud.githubusercontent.com/assets/11964962/14570372/c09edf7e-02f8-11e6-82c3-4173d34a60d4.png)

But once text in them gets too long, it just clips off the edges:
![image](https://cloud.githubusercontent.com/assets/11964962/14570357/b5e62524-02f8-11e6-9ca0-e1971f20f4c6.png)

And setting a max-width on flipster__item causes the item to move to the left and down and breaks navigation:
![image](https://cloud.githubusercontent.com/assets/11964962/14570415/edaac898-02f8-11e6-9234-d01a9bcd034c.png)

**Comment by shshaw** [comment]
Are you adding the `max-width` in your CSS or with dev tools? If you edit it on the fly in dev tools, you'll need to trigger a resize event. Simply changing your browser window size should do it.

**Comment by solarroger** [comment]
That was it exactly. Works fine after dragging the window. Thank you!
![image](https://cloud.githubusercontent.com/assets/11964962/14571301/5742ab3c-02fd-11e6-9a81-b26c6bcad3c3.png)

**Comment by shshaw** [comment]
Glad that helped! I was hoping that was all it was, since `max-width` has never posted a problem before :-)
