### ISSUE TITLE
Unordered list

### ISSUE THREAD

**Issue by atilkan** [drien/jquery-flipster#83]
**Document says**
nav: false,
    // [true|false|'before'|'after']
    // If not false, Flipster will build an unordered list of the items

**But**
It creates ordered list with numbers

![capture](https://cloud.githubusercontent.com/assets/1254613/14946741/2edc7eda-1030-11e6-9765-1d534f9d852b.PNG)

**Comment by shshaw** [comment]
Just to clarify: is the issue that it's numbered items in an unordered list when it should be an ordered list? 

I do think that should be switched to an ordered list, and the numbers should probably be +1 to better coordinate with what endusers might expect that the first slide is `1`, not `0`.

**Comment by atilkan** [comment]
Something is wrong, just reported.

**Comment by shshaw** [comment]
I'm just asking for clarification on what you found that was wrong.

**Comment by atilkan** [comment]
Why do you ask? I've put an image there. It shows the output. Number 1 is there but same color probably. That is not the point though. Document or Code something should to be switched.

**Comment by shshaw** [comment]
I'm asking for clarification. Your issue is that the nav is a `<ul>`, but it should be a `<ol>`?

The documentation and the code output match. An unordered list is output, and if the items do not have titles, then their index numbers are used as the nav item's content instead.

**Comment by shshaw** [comment]
Here's the output, coming out exactly as it's documented:
![screen shot 2016-05-02 at 1 48 10 pm](https://cloud.githubusercontent.com/assets/777155/14964128/88be5964-106c-11e6-9ca8-7c6d8032c94e.png)

**Comment by atilkan** [comment]
You are/ I am missing something here. 
Did you see this quote? "Flipster will build an unordered list of the items"

**Comment by shshaw** [comment]
`<ul>` is an HTML element which stands for 'unordered list'. The `nav` output puts the items in a `<ul>` (unordered list).

The nav items are an ordered list in that they are in order from first to last. Using a `<ol>` (ordered list) element is not a huge deal if you have titles for each slide ( 1. My First Slide, 2. Another Slide ), but if falling back to the default of the item's index (which starts at 0), you end up with some funny looking output ( 1. 0, 2. 1, 3. 2 ) unless you style it.  To avoid having numbers repeated or shown oddly from browser default styles, a `<ul>` (unordered list) element is used where the browser defaults of bullets are a bit more sensible. ( • 0, • 1, • 2 ).

The styles are included that would prevent the `<ol>` numbers from displaying, but do you have any specific reasons why `<ol>` should be used instead, if indeed that is what you are proposing?

Not trying to be patronizing with any of my wording, I'm just want to be sure that we're using the same language.

**Comment by atilkan** [comment]
I just expected to be bullets. I don't know why but it feels like what unordered means.

**Comment by shshaw** [comment]
Typically unordered list ( `<ul>` ) elements do display bullets. Flipster's default styles remove those bullets, though.

If you're looking for a [typical 'dot' navigation like a lot of sliders use](http://kenwheeler.github.io/slick/), then you just need to style the nav elements that way. Here's a [basic CodePen demo](http://codepen.io/shshaw/pen/xVQeWX?editors=0100) showing you how to style the nav as bullets.

[![screen shot 2016-05-03 at 10 50 45 am](https://cloud.githubusercontent.com/assets/777155/14989344/eb6f3ae6-111c-11e6-9807-466e64db329e.png)](http://codepen.io/shshaw/pen/xVQeWX?editors=0100)

**Comment by atilkan** [comment]
I appreciative your effort. Like you said default <ul> display bullets. But i understood why it is not bullet after seeing navigation style slider.
Thank you very much.
