### ISSUE TITLE
autoplay and loop together

### ISSUE THREAD

**Issue by SergiOnGit** [drien/jquery-flipster#84]
autoplay and loop doesn't work together and this is really necessary to be fixed

**Comment by shshaw** [comment]
I'm not sure what you mean. As you can see in [this demo](http://codepen.io/shshaw/pen/oxQowz?editors=0010) `loop` is true, and `autoplay` is on, and it's working as expected. How exactly are you setting your options?

**Comment by SergiOnGit** [comment]
oh sorry i had autoplay set to true not milliseconds

**Comment by shshaw** [comment]
No worries! Glad we got it sorted. Enjoy!
