### ISSUE TITLE
Why the carousel blinked when the document is loaded?

### ISSUE THREAD

**Issue by cooer83** [drien/jquery-flipster#86]
When I open the document or refresh it, the carousel show up and fade-in twice. (looks like blinking)
I also saw such that status in your demo site. 
Can it be modified to fade-in only once?

**Comment by shshaw** [comment]
What browser are you seeing this in? Are you sure you aren't initializing Flipster twice?

Fades in only once in Chrome.

[Demo](http://codepen.io/shshaw/pen/qOJWxR)

![demo](http://www.giphy.com/gifs/3o6EhMQEXcTEH6fenK)

**Comment by cooer83** [comment]
Thank you for your answer, it really helped and I solve it.
The difference between your codes and mine was that I loaded "jquery.flipster.min.js" file in "head tag".
I should have loaded it right behind "flipster" div.
