### ISSUE TITLE
Counter for items in flipster

### ISSUE THREAD

**Issue by NicolasVanhecke** [drien/jquery-flipster#87]
Is there a way to get the amount and index of the slides in flipster?
**For example** if you want to add some extra information like 'photo 3 of 13'. Which would be updated when you navigate to the next/previous slide. 

Thanks

**Comment by shshaw** [comment]
Currently, no, but you could use Navigation functionality with custom CSS ( hiding all nav items except current ) and use `data-flip-title` to get close to what you describe.

```
<div class="my-flipster">
    <ul>
        <li data-flip-title="Photo 1 of 13">...</li>
        <li data-flip-title="Photo 2 of 13">...</li>
...
```

Definitely not ideal. There should probably be some custom events triggered when items are changed. I don't know that there's currently a way to have callbacks whenever the item is changed.

**Comment by Reached** [comment]
Is this functionality something that is currently being worked on by any chance? :)

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
