### ISSUE TITLE
Veritcal carousel and slide angle.

### ISSUE THREAD

**Issue by Serpent6877** [drien/jquery-flipster#88]
Is it possible with CSS to do a Vertical carousel? And what about changing the angle of the secondary images? I am trying to emulate what is show in the attached image. 

Thanks!
![carousel](https://cloud.githubusercontent.com/assets/2003960/15998862/6a0c756e-30f6-11e6-93c8-8286b7de48ea.jpg)

**Comment by shshaw** [comment]
See #65. It's possible, but not what Flipster was built for. It's possible a future version will support that.

As for adjusting the angles, start with a theme from [flipster.css](https://github.com/drien/jquery-flipster/blob/master/dist/jquery.flipster.css) ( or the [.less files](https://github.com/drien/jquery-flipster/tree/master/src/less/themes) which are separated out ), and tweak the transform values to suit your design. `rotateY` will be what sets the angles.
