### ISSUE TITLE
insert url link

### ISSUE THREAD

**Issue by maxlore** [drien/jquery-flipster#89]
hello Drien, How I can insert url link in  submenus buttons? Thank you

**Comment by shshaw** [comment]
Are you referring to adding URLs in the Flipster nav that's generated, or making a Flipster item link to a URL?

Flipster Items themselves can be links, like this:

```js
<div class="my-flipster">
    <div>
        <a href="/url"> URL Link </a>
        <a href="/url"> URL Link </a>
        <div> Not linked </div>
        ...
    </div>
</div>
```

**Comment by maxlore** [comment]
Hi, thank for you response. I attach image explaining what I want to do. Thanks
![issue](https://cloud.githubusercontent.com/assets/19934035/16053753/62287468-326a-11e6-8567-da9a62536bad.jpg)

**Comment by shshaw** [comment]
Ah, yes. That's not currently how Flipster works. The navigation that Flipster builds is simply for navigating to a specific item.

You could possibly insert your own links into the nav to replace Flipsters, but there may be an `event.preventDefault()` or `event.stopPropagation()` that would block that.
