### ISSUE TITLE
Flipster draggable

### ISSUE THREAD

**Issue by calvinhill** [drien/jquery-flipster#90]
Hi 
Is it possible to make flipster draggable?

Thank you

**Comment by shshaw** [comment]
As in 'drag an item to reorder', not 'scroll through items with touch'? Support for drag-to-reorder is not built in. 

You may want to look at something like [Draggable](http://greensock.com/draggable) or [Dragula](https://github.com/bevacqua/dragula). You'll probably need to disable touch events on flipster and adapt your own support for scrolling through the list when you reach the edge of the container.
