### ISSUE TITLE
will not center single item

### ISSUE THREAD

**Issue by sugardave** [drien/jquery-flipster#91]
If flipster only has one item in it, it is always on the left edge of the container (not centered) and most of the css classes are not added to the container.  I have the situation where I am filtering collections of items and displaying them in flipster, but when my collection is only one item, it blows up.

I was looking at the codepen in issue #85 (http://codepen.io/eriqjaffe/pen/RadGLZ) and you can see what I mean if you remove all the <li>s but one and re-run it.  I expected the single tile to be in the center of the div.

**Comment by shshaw** [comment]
Currently flipster doesn't initialize if only one item is present. I can't remember specifically when that was implemented, but it was likely to prevent glitches with navigation and centering.

You can try commenting out [lines 618-621](https://github.com/drien/jquery-flipster/blob/master/src/jquery.flipster.js#L618-L621) to see if that works as you expect.

**Comment by sugardave** [comment]
Thanks, I will try it and let you know how it goes.  Currently embroiled in a different issue for same app 👍

**Comment by sugardave** [comment]
Unfortunately, the simple test fails.  It does center the tile, but only shows the middle third of it and I can't seem to make it 'refresh' to its full size.  It's probably something with less/css, but I'm not good at deciphering it all.

**Comment by sugardave** [comment]
I made this patch https://github.com/drien/jquery-flipster/pull/92

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
