### ISSUE TITLE
Flickering when the document is loaded

### ISSUE THREAD

**Issue by brainformatik** [drien/jquery-flipster#95]
hi @shshaw, 

i have the same issue as mentioned here #86.
- no flicker in chrome 51
- flicker in safari 9 and firefox 47

why it does not flicker in chrome, because this https://github.com/drien/jquery-flipster/blob/master/src/jquery.flipster.js#L646 event is not working in chrome except you implement an each function as a chaining command to trigger "load" on each element. 

why it does flicker in  safari and firefox, because this https://github.com/drien/jquery-flipster/blob/master/src/jquery.flipster.js#L646 event is executed and that https://github.com/drien/jquery-flipster/blob/master/src/jquery.flipster.js#L652 function is executed as well. finally the method show is executed twice.

**Comment by shshaw** [comment]
It may be as simple as adding a check for if Flipster has already been shown in the `show` function so that it doesn't get triggered twice. 

There's probably a better way to check on the image loading, as well. I know several browsers don't trigger that correctly.

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
