### ISSUE TITLE
Safari Compatibility

### ISSUE THREAD

**Issue by stokesbga** [drien/jquery-flipster#96]
Safari renders flipster elements really close together. Is there a fix for this? Im on safari 8.

![screen shot 2016-08-01 at 10 10 19 am](https://cloud.githubusercontent.com/assets/8782370/17296626/35daa21a-57d0-11e6-918f-d660044019f0.png)

**Comment by shshaw** [comment]
I think Safari 8 is just not handling the 3D transforms correctly. Perhaps a missing vendor prefix. 9.1 is the latest Safari version where Flipster works fine, any reason you're stuck on 8?

**Comment by drien** [comment]
Seems very likely vendor prefix related given that it definitely once worked on Safari 8. From the latest analytics on a property with quite a lot of traffic I'm seeing Safari 8 users as making up <2% of traffic, a number which will only get smaller.

**Comment by stokesbga** [comment]
Upgrading to safari 9 worked. Thanks!

**Comment by shshaw** [comment]
@drien It looks like the compiled CSS is not being autoprefixed. Or at least not autoprefixed in a way that includes `-webkit` prefixes that Safari 8 needs. Do know if the settings are right in the Gruntfile?
