### ISSUE TITLE
Firefox issues on transform

### ISSUE THREAD

**Issue by Reached** [drien/jquery-flipster#97]
Hi there,

Great plugin! I am experiencing a problem with Firefox at the moment though. 
I thought it was a problem with my code, however the problem is also present on the demo page in the Flipster Carousel demo:

http://brokensquare.com/Code/jquery-flipster/demo/

The issue is that when you change to the next slide, the slide sort of "jumps" or get resized (hard to explain). I tried to remove the perspective from the item 

`.flipster--coverflow .flipster__item`

Which seemed to do the trick, however it also removed the perspective effect. Are you able to reproduce this error?

I tested in Firefox 47 + 48 and the problem exists in both versions.

**Comment by Reached** [comment]
I have solved this issue by adding the following:

```
.flipster--carousel .flipster__item {
  perspective: 800px;
  transform-style: preserve-3d;
}
```

Hope this helps someone else in their adventures :)

**Comment by corey-hg** [comment]
Sad to report Firefox still has the same issue (it can be seen in the demo), and applying transform-style: preserve-3d; to the child element doesn't fix it.  

FF (for mac anyway) is having a bad habit of showing things as fixed after adding css to the inspector, but adding the css to the stylesheet and reloading shows the same issue.
