### ISSUE TITLE
Dynamic binding of flipster carousel card

### ISSUE THREAD

**Issue by swathigs** [drien/jquery-flipster#98]
I am using flipster carousel card in my application. When i bind the card values statically my card view is coming fine . When i dynamically get the values carousal classes are not getting generated. i am just getting a plane and spread cards.

[code.txt](https://github.com/drien/jquery-flipster/files/429360/code.txt)

**Comment by sugardave** [comment]
You have to do `flipster('index')` when you dynamically change the amount of items you want it to render.

**Comment by nehadhingra09** [comment]
did flipster('index'), stilll the css doesn't render in dynamic loading

**Comment by sugardave** [comment]
I only saw that in my app when there was just a single item.

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
