### ISSUE TITLE
How to create a circular carousel?

### ISSUE THREAD

**Issue by devalphabeta** [drien/jquery-flipster#99]
Hi.  How do I create a circular roundabout carousel like the one in this demo?  
see http://a.drien.com/jquery-flipster/demo5.html

Basically, when the last slide on the left becomes the first slide on the right, to give a circular carousel.
In the current version, the last slide on the left does not become the first slide on the right to give this circular carousel.

Thanks in advance.

Great work!

**Comment by shshaw** [comment]
This functionality changed a bit from the previous version. See #51
